#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          omxplayer-sync
# Required-Start:    $dhcp
# Required-Stop:     $dhcp
# Should-Start: 
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:  omxplayer synchro
# Description:
### END INIT INFO

movie_file=/media/usb0/movie.mp4

master_command="/home/pi/omxplayer-sync/omxplayer-sync2 -mu "
master_command_verbose="/home/pi/omxplayer-sync/omxplayer-sync2 -muv "
slave_command="/home/pi/omxplayer-sync/omxplayer-sync2 -lu "
slave_command_verbose="/home/pi/omxplayer-sync/omxplayer-sync2 -luv "

OUTPUT="/home/pi/omxplayer-sync.log"
master_file="/boot/master.txt"
kill_omx="/home/pi/omxplayer-sync/killOmx.sh"

outputMovie="/home/pi/movie.mp4"


sudo rm /tmp/omx*
echo "Waiting a bit"
sleep  8
echo "starting OMXPlayerSync"



# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script omxplayer_sync "
	if [ -f $movie_file ]
	then
		echo "movie exists on USB" 
		cp $movie_file $outputMovie
	else
		echo "movie doesn't exist on USB!" 
	fi

	
	if [ -f  $master_file ]
	then
		echo "Master"
		su - pi -c "$master_command $outputMovie  > $OUTPUT &"
	else
		echo "slave"
		su - pi -c "$slave_command $outputMovie > $OUTPUT &"
	fi
	
    ;;
  stop)
    echo "Stopping script omxplayer_sync"
    $kill_omx
    ;;
 console)
    echo "Starting script omxplayer_sync_master console" 
        if [ -f $movie_file ]
        then
                echo "movie exists on USB"
                cp $movie_file $outputMovie
        else
                echo "movie doesn't exist on USB!"
        fi
	
	if [ -f $master_file ]
	then
		$master_command_verbose $outputMovie &
	else
		$slave_command_verbose $outputMovie &
	fi
	;;
  *)
    echo "Usage: /etc/init.d/omxplayer_sync_master {start|stop|console}"
    exit 1
    ;;
esac

exit 0

